CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    opening_time TIME NOT NULL,
    closing_time TIME NOT NULL,
    max_orders_in_progress INTEGER NOT NULL CHECK (max_orders_in_progress > 0),
    automatic_pause BOOLEAN NOT NULL DEFAULT TRUE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ABERTA', 'FECHADA', 'PAUSADA'))
);
